server:
    port: 8802
    servlet:
        context-path: /biz

spring:

    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos

    datasource:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/itripdb
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    application:
        name: itrip-biz

#mybatis-plus的配置
mybatis-plus:
    configuration:
        #    日志打印实现
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
        #    驼峰命名法自动映射
        map-underscore-to-camel-case: true
    #    指定映射文件的路径
    mapper-locations: classpath*:/mapper/xml/*.xml
    #    别名
    type-aliases-package: com.hzl.entity
    #逻辑删除
    global-config:
        db-config:
            # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
            logic-delete-field: isDeleted
            # 逻辑已删除值(默认为 1)
            logic-delete-value: 1
            # 逻辑未删除值(默认为 0)
            logic-not-delete-value: 0