server:
  port: 80

spring:
  application:
    name: itrip-gateway
  cloud:
    # 注册到服务中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    # 指定路径规则
    gateway:
      routes:
        # 路由Id
        - id: itrip-auth
          # 路由目标的服务名
          uri: lb://itrip-auth
          # 路径匹配
          predicates:
            - Path=/auth/**

        - id: itrip-biz
          uri: lb://itrip-biz
          predicates:
            - Path=/biz/**

        - id: itrip-search
          uri: lb://itrip-search
          predicates:
            - Path=/search/**
      # 服务发现
      discovery:
        locator:
          #服务不区分大小写
          lower-case-service-id: true
          #开启服务发现
          enabled: true
  redis:
    host: localhost
    port: 6379


logging:
  level:
    root: info